- name:
  ansible.builtin.shell:
    cmd: curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1

- name:
  shell: . /etc/os-release

- name: 
  ansible.builtin.shell:  
    cmd: echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ focal main" | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null  

- name: install couchdb
  apt:
    pkg: couchdb
    update_cache: yes